apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ambuild.name" . }}
  labels: {{- include "ambuild.labels" . | nindent 4 }}
data:
  AMBUILD_WEB_TITLE: {{ .Values.title | quote }}
  AMBUILD_S3_BUCKET: {{ .Values.s3.bucket | quote }}
  AMBUILD_S3_PREFIX: {{ .Values.s3.prefix | quote }}
  S3_ENDPOINT_URL: {{ .Values.s3.endpointUrl | quote }}
  AWS_DEFAULT_REGION: {{ .Values.s3.region | quote }}
