apiVersion: v1
kind: Service
metadata:
  name: {{ include "ambuild.name" . }}
  labels: {{- include "ambuild.labels" . | nindent 4 }}
spec:
  selector: {{- include "ambuild.selector" . | nindent 4 }}
  ports:
    - {name: http, port: {{ .Values.service.port }}, targetPort: http}
